
title: General Dabblement
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dadams.ie/" # the base hostname & protocol for your site
github_username: donaladams
linkedin_username: williamdonaladams
# Build settings
markdown: kramdown

# permalink: none
permalink: /blog/:title

highlighter: rouge
