
title: General Dabblement
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.dadams.ie/" # the base hostname & protocol for your site
twitter_username: wdadams
github_username:  donaladams

# Build settings
markdown: kramdown

# permalink: none
permalink: /blog/:title

highlighter: rouge
